# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60e90da4f6ce787b6283620d219770b365d4f23ecc895feb0a2a0831f05d35d1ec03de63d7b262070bd17d46920cd680ea1cce754f18384dfd2ce651ca52578

test:
  secret_key_base: a243aa94fc6168cc2170de74da68517052ddb71e61e085a3f881140d3417fd823ef3a503144b0e0dcee24f5507b6fc9d82ef9499750d8930cecb369b2ab6c469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
